# This playbook creates a new volume and connects it to some
# defined instance

- name: create new gce persistent disk
  gce_pd:
    name: "{{ disk_name }}"
    # what instance to connect the disk to?
    instance_name: "{{ instance_name }}"
    size_gb: "{{ disk_size }}"
    disk_type: pd-ssd
    zone: "{{ instance.zone }}"
    mode: READ_WRITE
    state: active
    service_account_email: ""
    project_id: "{{ project_id }}"
    credentials_file: ""
