- name: configure mysql password
  command: debconf-set-selections <<< 'mysql-server mysql-server/root_password password {{ password }}'

- name: configure mysql password again
  command: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password {{ password }}'

- name: install mysql
  apt:
    name: "{{ item }}"
  with_items:
    - mysql-server
    - mysql-client

- name: install mysql python module
  apt:
    name: python-mysqldb

- name: start mysql
  service:
    name: mysql
    state: started
    enabled: true

- name: create database for owncloud
  mysql_db:
    name: owncloud
    login_host: localhost
    login_password: "{{ password }}"
    login_user: root

- name: create 
  mysql_user:
    user: owncloud
    password: "{{ password }}"
    host: "%"
    priv: 'owncloud.*:ALL'
    state: present

- name: replace
  shell: sed -i -e '43 s/^/#/' /etc/mysql/mysql.conf.d/mysqld.cnf
  
- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: true
