- name: install gluster client
  apt:
    name: glusterfs-client

- name: create directory to mount network drive
  file:
    name: /share/
    state: directory

- name: mount the network drive
  shell: mount -t glusterfs nfs01:/owncloud /share/