- name: install gluster client
  apt:
    name: glusterfs-client

- name: install gluster client
  apt:
    name: attr

- name: create directory to mount NFS
  file:
    path: /nfs/owncloud/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

# sudo mount -t nfs 35.237.213.137:/vars/www/owncloud /vars/www/owncloud
- name: mount the NFS
  mount:
    path: /nfs/owncloud/
    src: "{{ hostvars[groups['nfs'][0]]['ansible_default_ipv4']['address'] }}:/owncloud" # only for one server, not multiple
    fstype: glusterfs
    state: mounted

- name: symlink the mounted directory
  file:
    src: /nfs/owncloud
    dest: /var/www/owncloud
    owner: www-data
    group: www-data
    state: link



# todo: data

